// export const data = [
//     ['100xfx', 'Stas Zorin (Стас Зорин)', 'Мошенник'],
//     ['1с Option', '1с Option', 'Мошенник'],
//     ['alldayoption.com', 'Павел Абрамов (Pavel Abramov)', 'Мошенник'],
//     ['Armax Trade', 'Armax Trade', 'Мошенник'],
//     ['Asictrader.com', 'Victor Belov', 'Мошенник'],
//     ['bancdelux.com', 'Alena Arhipova', 'Мошенник'],
//     ['Bit4u', 'Алексей Фомин (Alexey Fomin)', 'Мошенник'],
//     ['BrokerCapital', 'Евгения (Evgeniya)', 'Мошенник'],
//     ['Capex24.com', 'Capex24.com', 'Мошенник'],
//     ['CMB (Capital Markets Bank)', 'CMB (Capital Markets Bank) Филипп Реб Яков Голан (Yakov Golan)', 'Мошенник'],
//     ['EveryOption', 'Илья Фролов (Ilya Frolov) Артем Бондаренко (Artyom Bondarenko) Павел Абрамов (Pavel Abramov) Sergio Demin', 'Мошенник']
//     ['ForenX', 'Алексей Смирнов (Alexey Smirnov) Александр Буров (Alexander Burov) Константин Шаров (Konstantin Sharov) Илья Фролов (Ilya Frolov) Антон Стефанцов (Anton Stefantsov) Вадим Прохоров (Vadim Prokhorov) Кирилл Абрамов (Kirill Abramov) Дмитрий Перекоптев (Dmytry Perekoptev)', 'Мошенник'],
//     ['Forex Corporate', 'Julio Diaz', 'Мошенник'],
//     ['fxinvesting.com', 'Vladislav Davydov (Владислав Давыдов) Petr Aleksandrovich (Пётр Александрович)', 'Мошенник'],
//     ['High Tech Trade', 'Алиса Смирнова (Alisa Smirnova)', 'Мошенник'],
//     ['investfond.org', 'investfond.org', 'Мошенник'],
//     ['arma-investing.com', 'Arma Investing', 'Мошенник'],
//     ['capitals.fund', 'Alexandr Belov (Александр Белов)', 'Мошенник'],
//     ['investingcase.com', 'Stas Esenin (Стас Есенин) Kristina Abramova', 'Мошенник'],
//     ['Investing Capital', 'investingcapital.com', 'Мошенник'],
//     ['investingpro.com', 'Sergey Mayakovskiy', 'Мошенник'],
//     ['investingpro.io', 'Sergey Mayakovskiy', 'Мошенник'],
//     ['keyoncapital.com', 'Alexander Voitz (Александр Войц) Vitaly Gennadievich (Виталий Геннадьевич)', 'Мошенник'],
//     ['metainvesting.com', 'Victor Krasnov Igor Bagrov', 'Мошенник'],
//     ['MxTrade', 'Davide Leali', 'Мошенник'],
//     ['NA', 'Кристина Соколовская (Cristina Sokholovskaya) Андрей Богданов (Andrey Bogdanov)', 'Мошенник'],
//     ['PlusFN', 'Алексей Смирнов (Alexey Smirnov) Александр Буров (Alexander Burov) Кирилл Абрамов (Kirill Abramov) Антон Савельев (Anton Saveliev) Игорь Калинин (Igor Kalinin)', 'Мошенник'],
//     ['ProTrade', 'Руслан (Ruslan) Дмитрий (Dmitry)', 'Мошенник'],
//     ['RFM - COMPANY', 'RFM - COMPANY', 'Мошенник'],
//     ['S24invest', 'NA', 'Мошенник'],
//     ['scamconsulting.com', 'Scam Consulting', 'Мошенник'],
//     ['SkyFX', 'Константин Шаров (Konstantin Sharov) Кирилл Абрамов (Kirill Abramov) Вадим Прохоров (Vadim Prokhorov)', 'Мошенник'],
//     ['Strade24 - Stock Trade 24 Inc.', 'Владимир Королёв (Vladimir Korolev)', 'Мошенник'],
//     ['Trade.crypto5.com', 'Vladimir Karger', 'Мошенник'],
//     ['UBroker', 'Илья Фролов (Ilya Frolov)', 'Мошенник'],
//     ['Uftbroker', 'Александр (Alexander)', 'Мошенник'],
//     ['ukmarkets.net', 'Екатерина', 'Мошенник'],
//     ['Union Traders Online', 'Алиса Смирнова (Alisa Smirnova)', 'Мошенник'],
//     ['updown.club.ru', 'Юлианна и Виктор Давыдов (Yulianna and Viktor Davydov)', 'Мошенник'],
//     ['vip-broker.org', 'Дмитрий (Dimitry) Максим (Maxim)', 'Мошенник'],
//     ['vipbroker.com', 'Михаил (Michail) Вероника (Veronika)', 'Мошенник'],
//     ['www.100investing.com', '-', 'Мошенник'],
//     ['www.byrix.com', 'Максим Волков (Maxim Volkov) Вениамин Семенов (Viniamin Semenov) Семён Стопов (Semen Stopov) Daniel Hidalgo', 'Мошенник'],
//     ['www.invest-di.com', 'Robert Bower', 'Мошенник'],
//     ['yardoption.com', 'Alexandr Abramov David Mirsky', 'Мошенник'],
//     ['Alpha Finans', '-', 'Мошенник'],
//     ['bnb-markets.com', 'Diana Ziskin', 'Мошенник'],
//     ['Cac400.com', 'Daniele Ricci', 'Мошенник'],
//     ['CaesarTrade.com', 'Adam Grande Benjamin Henderson Martin Cooper', 'Мошенник'],
//     ['Campbell International', 'NA', 'Мошенник'],
//     ['Casa de la Crypto', 'Albert Musk Conrad Jones', 'Мошенник'],
//     ['CFD Corporate', 'Edward Brooks Samuel Bale James Nicol', 'Мошенник'],
//     ['cfds100.com', 'Jeffey Peter', 'Мошенник'],
//     ['Chancellor Options', 'Gio Morgan', 'Мошенник'],
//     ['coinderix', '-', 'Мошенник'],
//     ['coinercrypt', '-', 'Мошенник'],
//     ['Cryptotexp.live', '-', 'Мошенник'],
//     ['DAX300', 'Roberto Manzo Angela', 'Мошенник'],
//     ['Fairstone', 'John William Harper', 'Мошенник'],
//     ['Forextradingcentral', 'Cristian Nucis', 'Мошенник'],
//     ['FX-Boutique', 'Paola Gómez', 'Мошенник'],
//     ['GCG24', 'Daniel O Nei', 'Мошенник'],
//     ['Golden Hill Capital', 'NA', 'Мошенник'],
//     ['GoProFinance.com', 'GoProFinance.com Sylvain Leroy', 'Мошенник'],
//     ['brinvestin.com.br', '-', 'Мошенник'],
//     ['cryptofxonline.com', 'Leonardo Massoni', 'Мошенник'],
//     ['globalinvest.credit', 'Emre Güven', 'Мошенник'],
//     ['investing.com.co', '-', 'Мошенник'],
//     ['becfd.com', 'Jack Nelson Michael Gallant', 'Мошенник'],
//     ['instagram.com/investing.comturkiye/', '-', 'Мошенник'],
//     ['investingcombrazil', '-', 'Мошенник'],
//     ['.wellingtoninv.com', 'Vanessa Santander', 'Мошенник'],
//     ['Invest 100 / EFG ACADEMY', 'Claudio Saula Victoria Santos', 'Мошенник'],
//     ['Investing online services', 'Sandro Ricci', 'Мошенник'],
//     ['Sandro RicciInvestingmining', 'Tania Moreira', 'Мошенник'],
//     ['Inwesting Yatırım', '-', 'Мошенник'],
//     ['italimarket.com', '-', 'Мошенник'],
//     ['LBLV or site https://investingbrasil.com/', 'Manuella Gomes Guilherme Alves', 'Мошенник'],
//     ['London Capital Trade', 'N/A', 'Мошенник'],
//     ['Master4x', 'Anna Moore', 'Мошенник'],
//     ['MisterBit.net', 'Davide Santorio', 'Мошенник'],
//     ['MX Solution', 'Hatem Ali Khaled salman', 'Мошенник'],
//     ['Mxbitos.com', '-', 'Мошенник'],
//     ['Privilege Trading', '-', 'Мошенник'],
//     ['PROFIT-TRADE', 'Dan Bauer', 'Мошенник'],
//     ['Rex Global International', 'Giuseppe Vicentini', 'Мошенник'],
//     ['SBI Social-b-investing', 'N/A', 'Мошенник'],
//     ['Sigma4trade', '-', 'Мошенник'],
//     ['Sternmarkets', '-', 'Мошенник'],
//     ['STOCK VIP Thailand', '-', 'Мошенник'],
//     ['Stox market', '-', 'Мошенник'],
//     ['Swap Investing', '-', 'Мошенник'],
//     ['Swissmain', 'Bradley Thomas Frank Fontana', 'Мошенник'],
//     ['Varterex or site http://varterex.com/', '-', 'Мошенник'],
//     ['Wacoins.com', '-', 'Мошенник'],
//     ['www.novatrades.com', 'Adam Conte', 'Мошенник'],
//     ['www.optioncm.com', 'N/A', 'Мошенник'],
//     ['YFX Capital', 'Oscar Leon', 'Мошенник']
// ]

export const data = [
    ['100xfx', ['Stas Zorin (Стас Зорин)'], 'Мошенник'],
    ['1с Option', ['1с Option'], 'Мошенник'],
    ['alldayoption.com', ['Павел Абрамов (Pavel Abramov)'], 'Мошенник'],
    ['Armax Trade', ['Armax Trade'], 'Мошенник'],
    ['Asictrader.com', ['Victor Belov'], 'Мошенник'],
    ['bancdelux.com', ['Alena Arhipova'], 'Мошенник'],
    ['Bit4u', ['Алексей Фомин (Alexey Fomin)'], 'Мошенник'],
    ['BrokerCapital', ['Евгения (Evgeniya)'], 'Мошенник'],
    ['Capex24.com', ['Capex24.com'], 'Мошенник'],
    ['CMB (Capital Markets Bank)', ['CMB (Capital Markets Bank), Филипп Реб Яков, Голан (Yakov Golan)'], 'Мошенник'],
    ['EveryOption', ['Илья Фролов (Ilya Frolov)', 'Артем Бондаренко (Artyom Bondarenko)', 'Павел Абрамов (Pavel Abramov)', 'Sergio Demin'], 'Мошенник'],
    ['ForenX', ['Алексей Смирнов (Alexey Smirnov)', 'Александр Буров (Alexander Burov)', 'Константин Шаров (Konstantin Sharov)', 'Илья Фролов (Ilya Frolov)', 'Антон Стефанцов (Anton Stefantsov)', 'Вадим Прохоров (Vadim Prokhorov)', 'Кирилл Абрамов (Kirill Abramov)', 'Дмитрий Перекоптев (Dmytry Perekoptev)'], 'Мошенник'],
    ['Forex Corporate', ['Julio Diaz'], 'Мошенник'],
    ['fxinvesting.com', ['Vladislav Davydov (Владислав Давыдов)', 'Petr Aleksandrovich (Пётр Александрович)'], 'Мошенник'],
    ['High Tech Trade', ['Алиса Смирнова (Alisa Smirnova)'], 'Мошенник'],
    ['investfond.org', ['investfond.org'], 'Мошенник'],
    ['arma-investing.com', ['Arma Investing'], 'Мошенник'],
    ['capitals.fund', ['Alexandr Belov (Александр Белов)'], 'Мошенник'],
    ['investingcase.com', ['Stas Esenin (Стас Есенин)', 'Kristina Abramova'], 'Мошенник'],
    ['Investing Capital', ['investingcapital.com'], 'Мошенник'],
    ['investingpro.com', ['Sergey Mayakovskiy'], 'Мошенник'],
    ['investingpro.io', ['Sergey Mayakovskiy'], 'Мошенник'],
    ['keyoncapital.com', ['Alexander Voitz (Александр Войц)', 'Vitaly Gennadievich (Виталий Геннадьевич)'], 'Мошенник'],
    ['metainvesting.com', ['Victor Krasnov', 'Igor Bagrov'], 'Мошенник'],
    ['MxTrade', ['Davide Leali'], 'Мошенник'],
    ['NA', ['Кристина Соколовская (Cristina Sokholovskaya)', 'Андрей Богданов (Andrey Bogdanov)'], 'Мошенник'],
    ['PlusFN', ['Алексей Смирнов (Alexey Smirnov)', 'Александр Буров (Alexander Burov)', 'Кирилл Абрамов (Kirill Abramov)', 'Антон Савельев (Anton Saveliev)', 'Игорь Калинин (Igor Kalinin)'], 'Мошенник'],
    ['ProTrade', ['Руслан (Ruslan)', 'Дмитрий (Dmitry)'], 'Мошенник'],
    ['RFM - COMPANY', ['RFM - COMPANY'], 'Мошенник'],
    ['S24invest', ['NA'], 'Мошенник'],
    ['scamconsulting.com', ['Scam Consulting'], 'Мошенник'],
    ['SkyFX', ['Константин Шаров (Konstantin Sharov)', 'Кирилл Абрамов (Kirill Abramov)', 'Вадим Прохоров (Vadim Prokhorov)'], 'Мошенник'],
    ['Strade24 - Stock Trade 24 Inc.', ['Владимир Королёв (Vladimir Korolev)'], 'Мошенник'],
    ['Trade.crypto5.com', ['Vladimir Karger'], 'Мошенник'],
    ['UBroker', ['Илья Фролов (Ilya Frolov)'], 'Мошенник'],
    ['Uftbroker', ['Александр (Alexander)'], 'Мошенник'],
    ['ukmarkets.net', ['Екатерина'], 'Мошенник'],
    ['Union Traders Online', ['Алиса Смирнова (Alisa Smirnova)'], 'Мошенник'],
    ['updown.club.ru', ['Юлианна и Виктор Давыдов (Yulianna and Viktor Davydov)'], 'Мошенник'],
    ['vip-broker.org', ['Дмитрий (Dimitry)', 'Максим (Maxim)'], 'Мошенник'],
    ['vipbroker.com', ['Михаил (Michail)', 'Вероника (Veronika)'], 'Мошенник'],
    ['www.100investing.com', ['-'], 'Мошенник'],
    ['www.byrix.com', ['Максим Волков (Maxim Volkov)', 'Вениамин Семенов (Viniamin Semenov)', 'Семён Стопов (Semen Stopov)', 'Daniel Hidalgo'], 'Мошенник'],
    ['www.invest-di.com', ['Robert Bower'], 'Мошенник'],
    ['yardoption.com', ['Alexandr Abramov', 'David Mirsky'], 'Мошенник'],
    ['Alpha Finans', ['-'], 'Мошенник'],
    ['bnb-markets.com', ['Diana Ziskin'], 'Мошенник'],
    ['Cac400.com', ['Daniele Ricci'], 'Мошенник'],
    ['CaesarTrade.com', ['Adam Grande', 'Benjamin Henderson', 'Martin Cooper'], 'Мошенник'],
    ['Campbell International', ['NA'], 'Мошенник'],
    ['Casa de la Crypto', ['Albert Musk', 'Conrad Jones'], 'Мошенник'],
    ['CFD Corporate', ['Edward Brooks', 'Samuel Bale', 'James Nicol'], 'Мошенник'],
    ['cfds100.com', ['Jeffey', 'Peter'], 'Мошенник'],
    ['Chancellor Options', ['Gio Morgan'], 'Мошенник'],
    ['coinderix', ['-'], 'Мошенник'],
    ['coinercrypt', ['-'], 'Мошенник'],
    ['Cryptotexp.live', ['-'], 'Мошенник'],
    ['DAX300', ['Roberto Manzo', 'Angela'], 'Мошенник'],
    ['Fairstone', ['John William Harper'], 'Мошенник'],
    ['Forextradingcentral', ['Cristian Nucis'], 'Мошенник'],
    ['FX-Boutique', ['Paola Gómez'], 'Мошенник'],
    ['GCG24', ['Daniel ONei'], 'Мошенник'],
    ['Golden Hill Capital', ['NA'], 'Мошенник'],
    ['GoProFinance.com', ['GoProFinance.com Sylvain Leroy'], 'Мошенник'],
    ['brinvestin.com.br', ['-'], 'Мошенник'],
    ['cryptofxonline.com', ['Leonardo Massoni'], 'Мошенник'],
    ['globalinvest.credit', ['Emre Güven'], 'Мошенник'],
    ['investing.com.co', ['-'], 'Мошенник'],
    ['becfd.com', ['Jack Nelson', 'Michael Gallant'], 'Мошенник'],
    ['instagram.com/investing.comturkiye/', ['-'], 'Мошенник'],
    ['investingcombrazil', ['-'], 'Мошенник'],
    ['.wellingtoninv.com', ['Vanessa Santander'], 'Мошенник'],
    ['Invest 100 / EFG ACADEMY', ['Claudio Saula', 'Victoria Santos'], 'Мошенник'],
    ['Investing online services', ['Sandro Ricci'], 'Мошенник'],
    ['Sandro RicciInvestingmining', ['Tania Moreira'], 'Мошенник'],
    ['Inwesting Yatırım', ['-'], 'Мошенник'],
    ['italimarket.com', ['-'], 'Мошенник'],
    ['LBLV or site https://investingbrasil.com/', ['Manuella Gomes', 'Guilherme Alves'], 'Мошенник'],
    ['London Capital Trade', ['N/A'], 'Мошенник'],
    ['Master4x', ['Anna Moore'], 'Мошенник'],
    ['MisterBit.net', ['Davide Santorio'], 'Мошенник'],
    ['MX Solution', ['Hatem Ali', 'Khaled salman'], 'Мошенник'],
    ['Mxbitos.com', ['-'], 'Мошенник'],
    ['Privilege Trading', ['-'], 'Мошенник'],
    ['PROFIT-TRADE', ['Dan Bauer'], 'Мошенник'],
    ['Rex Global International', ['Giuseppe Vicentini'], 'Мошенник'],
    ['SBI Social-b-investing', ['N/A'], 'Мошенник'],
    ['Sigma4trade', ['-'], 'Мошенник'],
    ['Sternmarkets', ['-'], 'Мошенник'],
    ['STOCK VIP Thailand', ['-'], 'Мошенник'],
    ['Stox market', ['-'], 'Мошенник'],
    ['Swap Investing', ['-'], 'Мошенник'],
    ['Swissmain', ['Bradley Thomas', 'Frank Fontana'], 'Мошенник'],
    ['Varterex or site http://varterex.com/', ['-'], 'Мошенник'],
    ['Wacoins.com', ['-'], 'Мошенник'],
    ['www.novatrades.com', ['Adam Conte'], 'Мошенник'],
    ['www.optioncm.com', ['N/A'], 'Мошенник'],
    ['YFX Capital', ['Oscar Leon'], 'Мошенник']
];
